Readme update
fossasia/badgemagic-app pull request #23
Opened 2024-05-08 08:27 UTC by justgruba

2024-05-09 13:53 UTC, Fadikk367 requested changes

2024-05-09 13:53 UTC, Fadikk367 commented on README.md
> +To run the project on iOS you need installed XCode and have a phisical device.
```suggestion
To run the project on iOS you need installed XCode and have a physical device since simulators don't support bluetooth.
```

2024-05-09 13:53 UTC, Fadikk367 commented on README.md
> +- Generate the native part of the app using the command:
```suggestion
- Build the app using. following commad: (It will generate `ios` directory containing native part of the app)
```

2024-05-09 13:53 UTC, Fadikk367 commented on README.md
> +- Open `BadgeMagic.xcworkspace` in Xcode, then in the 'Signing and Capabilities' section, set up Development Team and Bundle Identifier.
```suggestion
- Using Xcode open `BadgeMagic.xcworkspace` located inside generated `ios` directory, then in the 'Signing and Capabilities' section, set up Development Team (You personal one) and Bundle Identifier (you can add suffix with your name - it serves only for local development).
```

2024-05-09 13:53 UTC, Fadikk367 commented on README.md
> +- Check if the physical build destination is set up on the physical device (this may be useful to remove Push Notifications). If you have a different Apple ID between Xcode and your device, you need
```suggestion
- Check if the physical build destination is set up on the physical device (it may be necessary to remove Push Notifications).
```

2024-05-09 13:53 UTC, Fadikk367 commented on README.md
> +- If you still can't open the app, try deleting the `ios\.xcode.env.local` file. It may help :) [Bug description] (https://github.com/facebook/react-native/issues/39903#issuecomment-1847591269).
```suggestion
- If you still can't build the app, try deleting the `ios\.xcode.env.local` file. It may help :) [Bug description] (https://github.com/facebook/react-native/issues/39903#issuecomment-1847591269).
-  If you can't open app after installing in on you iPhone then probably you have a different Apple ID between Xcode and your iPhone. Please open Device Management settings and allow your Phone to run the app
```

2024-05-29 08:49 UTC, mariobehling approved these changes

2024-05-29 08:49 UTC, merged